import { formatFiles, generateFiles, installPackagesTask, joinPathFragments, names, Tree } from '@nrwl/devkit';
import { libraryGenerator } from '@nrwl/workspace/generators';
import { Schema } from '@nrwl/workspace/src/generators/library/schema';
import { DomainSchema, generateNestJsModule, getGeneratorMetaData } from '../base.generator';


export default async function (tree: Tree, schema: DomainSchema)
{
  const nameVariations = names(schema.name);
  const directory: string = 'domains';
  const projectName: string = `${directory}-${nameVariations.fileName}`;

  schema.projectName = projectName;

  // CREATE AND REGISTER LIBRARY WITH NX
  const librarySchema: Schema = {
    name: schema.name,
    directory: directory,
    standaloneConfig: true
  };

  await libraryGenerator(tree, librarySchema);

  // GET META DATA & PROJECT NEEDED TO GENERATE CONTENT FROM TEMPLATES
  const { templateModel, project } = getGeneratorMetaData(tree, schema);


  // CREATE NEST JS MODULES FOR EACH DOMAIN SUBFOLDER
  await generateNestJsModule(tree, projectName, templateModel.fileName);
  await generateNestJsModule(tree, projectName, 'application', '1_application');
  await generateNestJsModule(tree, projectName, 'infrastructure', '2_infrastructure');
  await generateNestJsModule(tree, projectName, 'use-cases', '3_use-cases');


  // generate folders and files from ./templates into the target path (project.sourceRoot)
  generateFiles(
    tree,
    joinPathFragments(__dirname, './templates'),
    project.sourceRoot,
    templateModel
  );

  // CLEANUP: delete the lib folder automatically generated by libraryGenerator above as it's not needed
  tree.delete(`${project.sourceRoot}/lib`);

  await formatFiles(tree);

  return () =>
  {
    installPackagesTask(tree);
  };
}
